services:
  pixel-db-api-dev:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ../:/app