services:
  api-dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ../:/app
    networks:
      - backend
  db-dev:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/data/postgres
    volumes:
      - db-dev:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend  
  minio-dev:
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "${MINIO_PORT}:${MINIO_PORT}"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    volumes:
      - minio-dev:/data/minio
    command: server /data/minio --console-address ":${MINIO_PORT}"
    networks:
      - backend     
volumes:
  db-dev:   
  minio-dev:     

networks:
  backend:
    name: PixelDB-dev-network
    external: true