FROM golang:1.25-rc-bookworm

WORKDIR /app

ENV GO111MODULE=on
ENV GOPROXY=direct

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY . .

CMD ["air", "-c", ".air.toml"]