basePath: /
host: localhost:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Pixel
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Pixel Schwanz
  version: "1.1"
paths: {}
swagger: "2.0"
